image: alpine:3.7

before_script:
  - apk update && apk add openssh-client bash

deploy-develop:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - echo -e "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

    - ssh gitlab@161.97.103.54 < /builds/ozitag/wordpress/{{PROJECT_NAME}}/scripts/deploy-develop.sh
  only:
    - develop

deploy-master:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - echo -e "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

    - ssh ozitag@{{PRODUCTION_HOST}} < /builds/ozitag/wordpress/{{PROJECT_NAME}}/scripts/deploy-master.sh
  only:
    - master