version: "3.4"

services:
  wordpress:
    container_name: ${APP_NAME}-wordpress
    restart: always
    working_dir: /var/www/app
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${APP_PORT}:80
    depends_on:
      - db
    volumes:
      - ./src:/var/www/app
    environment:
      CONTAINER_ROLE: fpm
      WEB_DOCUMENT_ROOT: /var/www/app/public
      WEB_PHP_TIMEOUT: 300
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_MAX_FILESIZE: 500M
      PHP_POST_MAX_SIZE: 500M
      PHP_MAX_EXECUTION_TIME: 18000dc
      SERVICE_NGINX_CLIENT_MAX_BODY_SIZE: "500M"
  db:
    container_name: ${APP_NAME}-db
    image: mysql:8
    restart: always
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress